### ISSUE TITLE
Add support for Gitlab repositories

### ISSUE THREAD

**Issue by UlisesGascon** [KoolTheba/openssf-scorecard-api-visualizer#152]
https://openssf.org/blog/2023/08/28/openssf-scorecard-launches-v4-12-with-support-for-gitlab/

**Comment by KoolTheba** [comment]
Fantastic @UlisesGascon! I'll work on that!!¡ 
Those are good news !! 😎

**Comment by KoolTheba** [comment]
Hi @UlisesGascon,
Back in the day the code was implemented to work with both platforms, as soon as the api was ready, so great news!
I'm going to work in small refinements and on improving the documentation for the community to know that the visualizer can be used also with gitlab repositories too.
